import React from 'react';

export const PrivacyPolicy = () => (
  <div className="min-h-screen bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-10"><h1 className="text-3xl font-serif font-bold text-primary mb-6">Privacy Policy</h1><div className="bg-white rounded-2xl border border-border-light p-8 prose prose-sm text-text-secondary"><p>At BloomSupply, your privacy is our priority. This policy describes how we collect, use, and protect your personal information.</p><h3 className="text-primary font-serif">Information We Collect</h3><p>We collect information you provide when creating an account, placing orders, or contacting us, including your name, email, phone number, and delivery address.</p><h3 className="text-primary font-serif">How We Use Your Information</h3><p>Your information is used to process orders, provide customer support, improve our services, and send you relevant updates about your orders.</p><h3 className="text-primary font-serif">Data Security</h3><p>We implement industry-standard security measures including SSL encryption and secure payment processing to protect your data.</p><h3 className="text-primary font-serif">Contact</h3><p>For any privacy concerns, email us at privacy@bloomsupply.com</p></div></div></div>
);

export const RefundPolicy = () => (
  <div className="min-h-screen bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-10"><h1 className="text-3xl font-serif font-bold text-primary mb-6">Refund & Returns Policy</h1><div className="bg-white rounded-2xl border border-border-light p-8 prose prose-sm text-text-secondary"><p>We want you to be completely satisfied with your purchase. If you're not happy, here's how we can help.</p><h3 className="text-primary font-serif">Freshness Guarantee</h3><p>If your flowers arrive damaged or wilted, contact us within 24 hours with photos. We'll send a replacement or issue a full refund.</p><h3 className="text-primary font-serif">Cancellation</h3><p>Orders can be cancelled within 2 hours of placing. After that, we begin processing and cannot guarantee cancellation.</p><h3 className="text-primary font-serif">Refund Process</h3><p>Approved refunds are processed within 5-7 business days to your original payment method.</p><h3 className="text-primary font-serif">Contact</h3><p>For refund requests, email returns@bloomsupply.com with your order number.</p></div></div></div>
);

export const About = () => (
  <div className="min-h-screen bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-10"><h1 className="text-3xl font-serif font-bold text-primary mb-6">About BloomSupply</h1><div className="bg-white rounded-2xl border border-border-light p-8 text-text-secondary text-sm leading-relaxed space-y-4"><p>BloomSupply is India's premium online flower delivery platform. We bring farm-fresh flowers directly to your doorstep, ensuring every petal arrives in perfect condition.</p><p>Founded with a passion for floriculture, we partner with the finest growers across India to curate collections that celebrate life's beautiful moments.</p><p>From everyday elegance to grand celebrations, our team of floral experts handpick each stem, crafting arrangements that speak the language of love, gratitude, and joy.</p><div className="grid grid-cols-3 gap-4 pt-4 border-t border-border-light"><div className="text-center"><div className="text-2xl font-serif font-bold text-accent">500+</div><div className="text-xs text-text-muted mt-1">Products</div></div><div className="text-center"><div className="text-2xl font-serif font-bold text-accent">50K+</div><div className="text-xs text-text-muted mt-1">Happy Customers</div></div><div className="text-center"><div className="text-2xl font-serif font-bold text-accent">100+</div><div className="text-xs text-text-muted mt-1">Cities</div></div></div></div></div></div>
);

export const Contact = () => (
  <div className="min-h-screen bg-surface"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-10"><h1 className="text-3xl font-serif font-bold text-primary mb-6">Contact Us</h1><div className="bg-white rounded-2xl border border-border-light p-8"><div className="grid grid-cols-1 sm:grid-cols-2 gap-8 mb-8"><div><h3 className="font-semibold text-primary mb-3">Get in Touch</h3><div className="space-y-2 text-sm text-text-secondary"><p>📧 hello@bloomsupply.com</p><p>📞 +91 98765 43210</p><p>📍 Mumbai, Maharashtra, India</p></div></div><div><h3 className="font-semibold text-primary mb-3">Business Hours</h3><div className="space-y-1 text-sm text-text-secondary"><p>Mon - Sat: 9:00 AM - 8:00 PM</p><p>Sunday: 10:00 AM - 6:00 PM</p></div></div></div><form className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><input placeholder="Your Name" className="w-full border border-border rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent" /><input placeholder="Your Email" type="email" className="w-full border border-border rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent" /></div><textarea placeholder="Your Message" rows={4} className="w-full border border-border rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent resize-none" /><button type="button" className="bg-primary text-white px-8 py-3 rounded-full font-semibold text-sm hover:bg-primary-light transition-colors">Send Message</button></form></div></div></div>
);
